version: "3.9"
services:
  web:
    image: nginx:1.25.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./app:/var/www/html
  postgres:
    image: postgres:latest
    container_name: webModuleDB
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./app/.env
volumes:
  postgresDB:
