# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#
# Default paths
#
home:
  path: /
  defaults: {_controller: 'App\Controller\General::home'}
contact:
  path: /contact
  defaults: {_controller: 'App\Controller\General::contact'}
question:
  path: /question
  defaults: {_controller: 'App\Controller\General::question'}
logout:
  path: /logout
  defaults: {_controller: 'App\Controller\Auth::logout'}
login:
  path: /login
  defaults: {_controller: 'App\Controller\OAuth\Github::github'}
#
# OAuth paths
#
# Github
github_redirect:
  path: /oauth/github/redirect
  defaults: {_controller: 'App\Controller\OAuth\Github::github'}
github_callback:
  path: /oauth/github/callback
  defaults: {_controller: 'App\Controller\OAuth\Github::callback'}
#
# API routes
#
# Auth (API routes releated to authentication)
logout-api:
  path: /api/auth/logout
  defaults: {_controller: 'App\Controller\Auth::logout'}
