# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#
# Default paths
#
home:
  path: /
  defaults: {_controller: 'App\Controller\General::home'}
contact:
  path: /contact
  defaults: {_controller: 'App\Controller\General::contact'}
question:
  path: /question
  defaults: {_controller: 'App\Controller\General::question'}
leaderboard:
  path: '/leaderboard'
  defaults: {_controller: 'App\Controller\General::leaderboard'}
logout:
  path: /logout
  defaults: {_controller: 'App\Controller\Auth::logout'}
login:
  path: /login
  defaults: {_controller: 'App\Controller\OAuth\Github::github'}
#
# OAuth paths
#
# Github
github_redirect:
  path: /oauth/github/redirect
  defaults: {_controller: 'App\Controller\OAuth\Github::github'}
github_callback:
  path: /oauth/github/callback
  defaults: {_controller: 'App\Controller\OAuth\Github::callback'}
#
# API routes
#
# Auth (API routes releated to authentication)
me-auth:
  path: /api/auth/me
  defaults: {_controller: 'App\Controller\Auth::me'}
logout-auth:
  path: /api/auth/logout
  defaults: {_controller: 'App\Controller\Auth::logout'}
#
# Question (API routes related to questions)
create-question:
  path: /api/question/create
  defaults: {_controller: 'App\Controller\Question::create'}
answer-question:
  path: /api/question/answer
  defaults: {_controller: 'App\Controller\Question::answer'}
#
# Background services
get-new-question:
  path: /api/background/question
  defaults: {_controller: 'App\Controller\Background\Question::getNewQuestion'}
